const BookActionType = {
    WRITE_RECORD_START = "WRITE_RECORD_START",
    WRITE_RECORD_SUCESS = "WRITE_RECORD_SUCESS",
    WRITE_RECORD_FAILURE = "WRITE_RECORD_FAILURE",
    REMOVE_RECORD_START = "REMOVE_RECORD_START",    
    REMOVE_RECORD_SUCESS = "REMOVE_RECORD_SUCESS",  
    REMOVE_RECORD_FAILURE = "REMOVE_RECORD_FAILURE",    
    GET_RECORDS_START = "GET_RECORDS_START",
    GET_RECORDS_SUCESS = "GET_RECORDS_SUCESS",
    GET_RECORDS_FAILURE = "GET_RECORDS_FAILURE",
}

export default BookActionType;