const MemberActionTypes = {
  ADD_MEMBER_START: "ADD_MEMBER_START",
  ADD_MEMBER_SUCESS: "ADD_MEMBER_SUCESS",
  ADD_MEMBER_FAILURE: "ADD_MEMBER_FAILURE",
  REMOVE_MEMBER_START: "REMOVE_MEMBER_START",
  REMOVE_MEMBER_SUCESS: "REMOVE_MEMBER_SUCESS",
  REMOVE_MEMBER_FAILURE: "REMOVE_MEMBER_FAILURE",
  GET_MEMBER_START: "GET_MEMBER_START",
  GET_MEMBER_SUCESS: "GET_MEMBER_SUCESS",
  GET_MEMBER_FAILURE: "GET_MEMBER_FAILURE",
};
export default MemberActionTypes;
