const UserActionTypes = {
  GOOGLE_SIGNIN_START: "GOOGLE_SIGNIN_START",
  GOOGLE_SIGNIN_SUCESS: "GOOGLE_SIGNIN_SUCESS",
  GOOGLE_SIGNIN_FAILURE: "GOOGLE_SIGNIN_FAILURE",
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  SIGNING_OUT_START: "SIGNING_OUT_START",
  SIGNING_OUT_SUCESS: "SIGNING_OUT_SUCESS",
  SIGNING_OUT_FAILURE: "SIGNING_OUT_FAILURE",
};

export default UserActionTypes;
