const UserActionTypes = {
  GOOGLE_SIGNIN_START: "GOOGLE_SIGNIN_START",
  GOOGLE_SIGNIN_SUCESS: "GOOGLE_SIGNIN_SUCESS",
  GOOGLE_SIGNIN_FAILURE: "GOOGLE_SIGNIN_FAILURE",
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
};

export default UserActionTypes;
